apiVersion: v1
kind: Service
metadata:
  name: apache-demo-api
  labels:
    app: apache-demo-api
spec:
  type: NodePort
  selector:
    app: apache-demo-api
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30100
